AllCops:
  Exclude:
    - vendor/**/*
    - public/**/*
    - db/**/*
    - config/**/*
    - bin/**/*

Metrics/LineLength:
  Max: 170

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 21
#test
Style/Documentation:
  Enabled: false
#test
#test
Style/ClassAndModuleChildren:
  Enabled: false